name: Compatibility Check
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  forward-compatibility:
    name: check-compatibility
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Check Latest Dependencies
        run: |
          cd ..
          git clone https://github.com/sei-protocol/sei-chain.git
          git clone https://github.com/sei-protocol/sei-tendermint.git
          git clone https://github.com/sei-protocol/sei-iavl.git
          cd sei-chain
          go mod edit -replace github.com/cosmos/iavl=../sei-iavl
          go mod edit -replace github.com/tendermint/tendermint=../sei-tendermint
          go mod edit -replace github.com/cosmos/cosmos-sdk=../sei-cosmos
          go mod tidy
          make install